[package]
name = "mini_os"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "mini_os"
test = false
bench = false

[unstable]
build-std = ["core", "compiler_builtins"]

